Intergation Testing
henrycode460/myblog pull request #9
Opened 2022-10-18 12:47 UTC by henrycode460

This branch contains the followings:

- Integration testing for the user_index and user_show view
- Integration testing for the post_index and the post_show

2022-10-19 09:20 UTC, ShadyShawkat requested changes
## Hi @henrycode460, 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight
- All linters are passing ✔️ 
- Correct use of GitFlow ✔️ 
- Descriptive commit messages ✔️ 
- Professional looking pull request ✔️ 

![Image](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Required Changes ♻️
- [ ] Please make sure that the N+1 problem is fixed when fetching all the posts and their comments, as per [this](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/intergration_spec_and_n_1_project.md#:~:text=Make%20sure%20that%20the%20N%2B1%20problem%20is%20solved%20when%20fetching%20all%20posts%20and%20their%20comments%20for%20a%20user.%20This%20is%20the%20corresponding%20wireframe) requirement.
- [ ] Kindly add more tests for the posts index and show pages, as per the given requirements.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-19 09:56 UTC, petushka1 commented
Hello.
Kindly please check my requirement 
User post index page:

I can see the user's profile picture.
I can see the user's username.
I can see the number of posts the user has written.
I can see a post's title.
I can see some of the post's body.
I can see the first comments on a post.
I can see how many comments a post has.
I can see how many likes a post has.
I can see a section for pagination if there are more posts than fit on the view.
When I click on a post, it redirects me to that post's show page.
Post show page:

I can see the post's title.
I can see who wrote the post.
I can see how many comments it has.
I can see how many likes it has.
I can see the post body.
I can see the username of each commentor.
I can see the comment each commentor left.

I was adjusting some of _path to make sure all cases are covered and correspond to a specific layout
All these test case are covered in a single file features/user_post_spec.rb

2022-10-19 10:13 UTC, andersonlebon requested changes
## Hi @henrycode460 

Good job so far! I know you have worked hard on making this milestone But  There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
## Required Changes ♻️

- [ ] Kindly check comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-19 10:13 UTC, andersonlebon commented on spec/views/user_index_spec.rb
> +end
- [ ] Kindly Fix this failing test in your view you view Before going to the next milestone

![image](https://user-images.githubusercontent.com/65068771/196661839-58b119a3-4db2-4c4a-9979-e0a6d6b44127.png)

2022-10-19 10:13 UTC, andersonlebon commented on spec/requests/posts_spec.rb
> +# end
- [ ] Kindly Uncomment your previous tests this will allow you to know that your project still has the same functionality(no falling tests) when a new feature is added.

2022-10-19 14:23 UTC, RolandM99 approved these changes
<h1>Status: Approve 🥇 ✔</h1>
Hi @henrycode460, 

### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-19 14:23 UTC, RolandM99 commented on app/controllers/posts_controller.rb
> +    @posts = @user.posts.includes(:comments)
- ✔️  Great job solving the N+1 problem as requested by the previous reviewer.

2022-10-20 08:20 UTC, TedLivist commented
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @petushka1, @henrycode460,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You are submitting a pair-programming project that has been approved. Kindly note that for this project you should also work on your other partner's repo and create a PR from there.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-10-20 08:28 UTC, Davidosky007 reviewed
Hi @c3c1l1a 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't follow the proper work and submit mode 

> You should implement the above requirements in all repositories in your pair-programming group. That means that each group member needs to open a new pull request in their repo.
We will check the commit history to make sure that everybody has contributed code on each project.
You should ask for a review and submit this activity individually. [Check the submit mode requirement here](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/intergration_spec_and_n_1_project.md#:~:text=You%20should%20implement,this%20activity%20individually.)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-10-21 09:38 UTC, merged